command:
  moon: "&9&lMOON &f%star% &eThis server is &arunning &9&l%name% &f%version%&9."
  rank:
    help:
      - "&7&m-------------------------------------------------"
      - "&9&lRank Commands"
      - ""
      - "&f%star% &9/rank create <rank> &f- &7Create a rank"
      - "&f%star% &9/rank delete <rank> &f- &7Delete a rank"
      - "&f%star% &9/rank list &f- &7List of the current ranks and information"
      - "&f%star% &9/rank displayname <rank> <displayName> &f- &7Set the display name of a rank"
      - "&f%star% &9/rank prefix <rank> <prefix> &f- &7Set the prefix of a rank"
      - "&f%star% &9/rank color <rank> <color> &f- &7Set the color of a rank"
      - "&f%star% &9/rank weight <rank> <weight> &f- &7Set the weight of a rank"
      - "&f%star% &9/rank addpermission <rank> <permission> &f- &7Add a permission to a rank"
      - "&f%star% &9/rank removepermission <rank> <permission> &f- &7Remove a permission from a rank"
      - "&7&m-------------------------------------------------"
    already_exists: "&cThis rank already exists."
    doesnt_exist: "&cSorry but we couldn't find the rank you were looking for."
    create: "&9&lMOON &f%star% &eYou have &acreated &erank &f%rank%"
    delete: "&9&lMOON &f%star% &eYou have &cdeleted &erank &f%displayName%"
    displayName: "&9&lMOON &f%star% &eYou have &aupdated &ethe display name of rank &f%rank% &eto &f%displayName%"
    prefix: "&9&lMOON &f%star% &eYou have &aset &ethe prefix of rank &f%displayName% &eto &f%prefix%"
    color: "&9&lMOON &f%star% &eYou have &aupdated &ethe color of rank &f%displayName% &eto &f%color%"
    weight: "&9&lMOON &f%star% &eYou have &aupdated &ethe weight of rank &f%displayName% &eto &f%weight%"
    info:
      - "&cPrefix &f%star% %prefix%"
      - "&cColor &f%star% %color%"
      - "&cWeight &f%star% %weight%"
    grant: "&9&lMOON &f%star% &eYou have &agranted &ethe rank &f%rank% &eto &f%profile%"
    permission:
      add: "&9&lMOON &f%star% &eYou have &aadded &ethe permission &f%permission% &eto rank &f%rank%"
      remove: "&9&lMOON &f%star% &eYou have &cremoved &ethe permission &f%permission% &eto rank &f%rank%"
  gamemode: "&9&lMOON &f%star% &eYou have &aupdated &eyour gamemode to &6%gameMode%&e."
  teleport: "&9&lMOON &f%star% &eYou have &ateleported &eto &f%target%&e."
  teleportHere: "&9&lMOON &f%star% &eYou have &ateleported &6%target% &eto &6%player%&e."
  fly:
    enabled: "&9&lMOON &f%star% &eYou have &aenabled &eflight."
    disabled: "&9&lMOON &f%star% &eYou have &cdisabled &eflight."
  tag:
    help:
      - "&7&m----------------------------------------------------"
      - "&a&lTag Commands"
      - ""
      - "&f%star% &a/tag create <tag> &f- &7Create a tag"
      - "&f%star% &a/tag delete <tag> &f- &7Delete a tag"
      - "&f%star% &a/tag prefix <tag> <prefix> &f- &7Set the prefix of a tag"
      - "&f%star% &a/tag addpermission <tag> <permission> &f- &7Add a permission to a tag"
      - "&f%star% &a/tag removepermission <tag> <permission> &f- &7Remove a permission from a tag"
      - "&f%star% &a/tags &f- &7Information on the available tags"
      - "&7&m----------------------------------------------------"
    create: "&9&lMOON &f%star% &eYou have &acreated &etag &a%tag%"
    delete: "&9&lMOON &f%star% &eYou have &cdeleted &etag &a%tag%"
    prefix: "&9&lMOON &f%star% &eYou have &aset &ethe prefix of tag &a%tag% &eto &f%prefix%"
    permission:
      add: "&9&lMOON &f%star% &eYou have &aadded &ethe permission &f%permission% &eto rank &a%tag%"
      remove: "&9&lMOON &f%star% &eYou have &cremoved &ethe permission &f%permission% &eto rank &a%tag%"
    already_exists: "&cThis rank already exists."
    doesnt_exist: "&cSorry but we couldn't find the rank you were looking for."
  punishment:
    couldnt_find: "&cSorry we couldn't find any punishments from this player."
    type:
      kick: "&f%playerExecuted% &ahas been kicked by &f%executor%"
      ban: "&f%playerExecuted% &ahas been banned by &f%executor%"
      unban: "&f%playerExecuted% &ahas been unbanned by &f%executor%"

player_doesnt_exist: "&cSorry but we couldn't find the player you were looking for."