command:
  rank:
    help:
      - "&7&m--------------------------------------"
      - "&9&lRank Commands"
      - ""
      - "&9/rank create <rank>"
      - "&9/rank delete <rank>"
      - "&9/rank list"
      - "&9/rank displayname <rank> <displayName>"
      - "&9/rank prefix <rank> <prefix>"
      - "&9/rank color <rank> <color>"
      - "&9/rank weight <rank> <weight>"
      - "&7&m--------------------------------------"
    already_exists: "&cThis rank already exists."
    doesnt_exist: "&cSorry but we couldn't find the rank you were looking for."
    create: "&9&lMOON &f%right_arrow% &eYou have &acreated &erank &f%rank%"
    delete: "&9&lMOON &f%right_arrow% &eYou have &cdeleted &erank &f%displayName%"
    displayname: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe display name of rank &f%rank% &eto &f%displayName%"
    prefix: "&9&lMOON &f%right_arrow% &eYou have &aset &ethe prefix of rank &f%displayName% &eto &f%prefix%"
    color: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe color of rank &f%displayName% &eto &f%color%"
    weight: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe weight of rank &f%displayName% &eto &f%weight%"
    info:
      - "&cPrefix &f%right_arrow% %prefix%"
      - "&cColor &f%right_arrow% %color%"
      - "&cWeight &f%right_arrow% %weight%"
  grant: "&9&lMOON &f%right_arrow% &eYou have &agranted &ethe rank &f%rank% &eto &f%profile%"