command:
  moon: "&eThis server is &arunning &9&l%name% &f%version%&9."
  rank:
    help:
      - "&7&m-------------------------------------------------"
      - "&9&lRank Commands"
      - ""
      - "&f%right_arrow% &9/rank create <rank> &7- &fCreate a rank"
      - "&f%right_arrow% &9/rank delete <rank> &7- &fDelete a rank"
      - "&f%right_arrow% &9/rank list &7- &fList of the current ranks and information"
      - "&f%right_arrow% &9/rank displayname <rank> <displayName> &7- &fSet the display name of a rank"
      - "&f%right_arrow% &9/rank prefix <rank> <prefix> &7- &fSet the prefix of a rank"
      - "&f%right_arrow% &9/rank color <rank> <color> &7- &fSet the color of a rank"
      - "&f%right_arrow% &9/rank weight <rank> <weight> &7- &fSet the weight of a rank"
      - "&f%right_arrow% &9/rank addpermission <rank> <permission> &7- &fAdd a permission to a rank"
      - "&f%right_arrow% &9/rank removepermission <rank> <permission> &7- &fRemove a permission from a rank"
      - "&7&m-------------------------------------------------"
    already_exists: "&cThis rank already exists."
    doesnt_exist: "&cSorry but we couldn't find the rank you were looking for."
    create: "&9&lMOON &f%right_arrow% &eYou have &acreated &erank &f%rank%"
    delete: "&9&lMOON &f%right_arrow% &eYou have &cdeleted &erank &f%displayName%"
    displayname: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe display name of rank &f%rank% &eto &f%displayName%"
    prefix: "&9&lMOON &f%right_arrow% &eYou have &aset &ethe prefix of rank &f%displayName% &eto &f%prefix%"
    color: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe color of rank &f%displayName% &eto &f%color%"
    weight: "&9&lMOON &f%right_arrow% &eYou have &aupdated &ethe weight of rank &f%displayName% &eto &f%weight%"
    info:
      - "&cPrefix &f%right_arrow% %prefix%"
      - "&cColor &f%right_arrow% %color%"
      - "&cWeight &f%right_arrow% %weight%"
    grant: "&9&lMOON &f%right_arrow% &eYou have &agranted &ethe rank &f%rank% &eto &f%profile%"
    permission:
      add: "&9&lMOON &f%right_arrow% &eYou have &aadded &ethe permission &f%permission% &eto rank &f%rank%"
      remove: "&9&lMOON &f%right_arrow% &eYou have &cremoved &ethe permission &f%permission% &eto rank &f%rank%"